# GET SENTENCE FROM USER
sentence = input('Please provide a sentence to convert: ').strip()

# SPLIT SENTENCE INTO WORDS

# LOOP THROUGH WORDS AND CONVERT THEM INTO PIG-LATIN

# STICK THE WORDS BACK TOGETHER INTO SENTENCE

# OUTPUT THE FINAL STRING